apiVersion: apps/v1
kind: Deployment
metadata:
  name: es-node
  labels:
    type: es
spec:
  replicas: 1
  selector:
    matchLabels:
      type: es
  template:
    metadata:
      labels:
        type: es
    spec:
      terminationGracePeriodSeconds: 300
      initContainers:
      - name: fix-the-volume-permission
        image: busybox
        command:
        - sh
        - -c
        - chown -R 1000:1000 /usr/share/elasticsearch/data
        securityContext:
          privileged: true
      containers:
      - name: c2mon-es-node
        image: docker.io/justinamary/elastic_image:latest
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: tcp
        resources:
          requests:
            memory: 4Gi
          limits:
            memory: 6Gi
        env:
          - name: cluster.name
            value: elasticsearch-cluster
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: discovery.zen.ping.unicast.hosts
            value: "elasticsearch-0.es.default.svc.cluster.local,elasticsearch-1.es.default.svc.cluster.local,elasticsearch-2.es.default.svc.cluster.local"
          - name: ES_JAVA_OPTS
            value: -Xms4g -Xmx4g
        # volumeMounts:
        # - name: data
        #   mountPath: /usr/share/elasticsearch/data
  # volumeClaimTemplates:
  # - metadata:
  #     name: data
  #   spec:
  #     accessModes:
  #       - ReadWriteOnce
  #     storageClassName: ssd
  #     resources:
  #       requests:
  #         storage: 10Gi