apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-node
spec:
  serviceName: es
  replicas: 1
  selector:
    matchLabels:
      type: es
  template:
    metadata:
      labels:
        type: es
      name: c2mon-es-node
    spec:
      terminationGracePeriodSeconds: 300
      initContainers:
      - name: fix-the-volume-permission
        image: busybox
        command:
        - sh
        - -c
        - chown -R 1000:1000 /usr/share/elasticsearch/data
        securityContext:
          privileged: true
      containers:
      - image: cern/c2mon-ext:elasticsearch-5.6-c2mon-1.9.3-SNAPSHOT
        name: c2mon-es-node
        env:
        - name: namespace
          valueFrom:
           fieldRef:
            fieldPath: metadata.namespace
        - name: node.name
          valueFrom:  
           fieldRef:
            fieldPath: metadata.name
        - name: cluster.name
          value: c2mon
        - name: network.host
          value: "0.0.0.0"
        # Required in ES 5.6 images, as they don't pick up ENV config properly
        args: ["-Enode.name=$(node.name)",
               "-Ecluster.name=$(cluster.name)",
               "-Enetwork.host=$(network.host)",
               "-Ediscovery.type=single-node"]
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data       
        ports:
        - containerPort: 9200
        - containerPort: 9300
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: es
spec:
  clusterIP: None
  ports:
    - name: serving
      port: 9200
    - name: node-to-node
      port: 9300
  selector:
    type: es
